
spring:
  application:
    name: APIGATEWAY

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/*,/users
        - id: ratingservice
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/*,/ratings,/ratings/hotel/*
        - id: hotelservice
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/*,/hotels